apiVersion: apps/v1
kind: Deployment

metadata:
  name: task-management-deployment
  namespace: tms-ns
  labels:
    app: task-management

spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-management

  template:
    metadata:
      labels:
        app: task-management

    spec:
      containers:
      - name: tms-container
        image: sauravmishra07/ems:tag
        ports:
          - containerPort: 80

        resources: 
          requests: 
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"

