apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: tms-autoscaling
  namespace: tms-ns

spec: 
  scaleTargateRef: 
    apiVersion: app/v1
    kind: Deployment
    name: task-management-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics: 
  - type: Resource
    resource:
      name: cpu
      target: 
        type: Utilization
        avarageUtilization: 70
  - type: Resource
    resource: 
      name: memory
      target: 
        type: Utilization
        avarageUtilization: 80